import os

import numpy as np
import pandas as pd
import xarray as xr
from scipy.optimize import minimize
import bucket_model as bm
import constants as const

REGION_IDS = range(31, 69)  # Drought region IDs from 31 to 68
YEARS = range(1991, 2026)


def get_average_coordinates(region_id):
    id = region_id - 30
    path = f"data/trockenheit_grenzcoord/data_region{id}.csv"
    region_coords = pd.read_csv(path, sep=";")
    return region_coords["Easting"].mean(), region_coords["Northing"].mean()


def load_and_prepare_data(region_id, year):
    # 1. Load Rainfall
    file_path = f"data/rhiresD/ogd-surface-derived-grid-archive.rhiresd_ch01h.swiss.lv95_{year}0101000000_{year}1231000000.nc"
    if not os.path.exists(file_path):
        return None, None

    ds = xr.open_dataset(file_path)
    avg_e, avg_n = get_average_coordinates(region_id)
    rainfall = np.nan_to_num(
        ds["RhiresD"].sel(E=avg_e, N=avg_n, method="nearest").values, nan=0.0
    )

    # 2. Load BAFU and Interpolate to Daily
    bafu = pd.read_csv(
        "data/soil_moisture_history/weekly_historic_regions.csv",
        sep=";",
        skiprows=3,
        parse_dates=["measured_at"],
        dayfirst=True,
    )
    bafu_reg = bafu[bafu["drought_region_id"] == region_id].copy()
    bafu_reg = bafu_reg[bafu_reg["measured_at"].dt.year == year].set_index(
        "measured_at"
    )

    if len(bafu_reg) < 5:
        return None, None  # Skip if insufficient data

    rainfall_series = pd.Series(
        rainfall, index=pd.date_range(start=f"{year}-01-01", periods=len(rainfall))
    )

    # 1. Perform the interpolation
    interpolated = (
        bafu_reg["soil_moisture_ufc"].resample("D").interpolate(method="linear") / 100.0
    )

    # 2. Create the Series using the index generated by the interpolation itself
    # This automatically matches the length (e.g., 358) to the values
    daily_target = pd.Series(interpolated.values, index=interpolated.index)
    return rainfall_series, daily_target


def objective(params, rainfall, target):
    d_rate, et_rate = params

    # 1. Run simulation (result is a numpy array)
    sim_array = bm.calculate_daily_saturation(
        rainfall.values,
        n=const.N,
        n_perp=const.H_PERP,
        m0=target.iloc[0],
        drainage_rate=d_rate,
        et_rate=et_rate,
    )

    # 2. Create Series WITHOUT forcing the rainfall index onto it
    # We use the target's index directly to ensure we ONLY compare existing data
    sim_series = pd.Series(sim_array[: len(target)], index=target.index)

    # 3. Calculate error directly (no concat needed if index is shared)
    error = (sim_series - target) ** 2

    return np.mean(error.dropna())


# --- EXECUTION ---
results = []
for rid in REGION_IDS:
    region_params = []
    for yr in YEARS:
        print(f"Processing Region {rid}, Year {yr}...")
        rf, target = load_and_prepare_data(rid, yr)
        if rf is None or len(target) < 5:
            print(f"LOG: Skipping Region {rid}, Year {yr} due to insufficient data.")
            continue

        res = minimize(
            objective,
            x0=[0.05, 0.5],
            args=(rf, target),
            bounds=[(0.01, 0.3), (0.0, 2.0)],
        )
        region_params.append(res.x)

    if region_params:
        avg_params = np.mean(region_params, axis=0)
        results.append(
            {"region_id": rid, "drainage": avg_params[0], "et": avg_params[1]}
        )

pd.DataFrame(results).to_csv("calibration_results.csv", index=False)
print("Calibration complete. Results saved to 'calibration_results.csv'.")
